version: '3'

services:

    mariadb:
        image: mariadb:latest
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123
        volumes:
            - ./docker/my-mysql-db:/var/lib/mysql

    redis:
        image: redis:latest
        command: redis-server
        volumes:
            - ./docker/my-redis:/var/lib/redis
            - ./docker/redis-config:/usr/local/etc/redis/redis.conf
        ports:
            - 6379:6379
